---
apiVersion: app/v1 
kind: ReplicaSet
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 5
  selector:
    matchLabels:
      app: jenkins 
  template:
    metadata:
      name: jenkins
      labels: 
        app: jenkins 
        ver: "1.23"
    spec:
      containers:
        - name: jenkins 
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
              protocol: TCP
      initContainers:
        - name: alpine 
          image: alpine:3.16
          command: ["ping", "-c", "4", "google.com" ]