---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxpod
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        ver: "1.23"
    spec: 
      containers: 
        - name: nginxcontainer
          image: nginx:1.23
          ports: 
            - containerPort: 80
              protocol: TCP 
  
