apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc1
spec:
  type: NodePort
  selector:
    app: nginx 
    ver: "1.0"
  ports: 
    - name: webport1
      port: 35000
      targetPort: 80
      nodePort: 32002