---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers: 
    - image: jenkins/jenkins:lts-jdk11
      name: jenkins-container
      ports: 
        - containerPort: 8080
          protocol: TCP
    - image: nginx:1.23
      name: nginx-container
      ports:
        - containerPort: 80
          protocol: TCP